### ISSUE TITLE
undefined method `commit' for #<Array:xxx> with pronto 0.8.1

### ISSUE THREAD

**Issue by doits** [siebertm/pronto-coffeelint#7]
```
NoMethodError: undefined method `commit' for #<Array:xxx>
  /Users/markus/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pronto-0.8.1/lib/pronto/runners.rb:20:in `block in run'
  /Users/markus/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pronto-0.8.1/lib/pronto/runners.rb:13:in `each'
  /Users/markus/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pronto-0.8.1/lib/pronto/runners.rb:13:in `run'
  /Users/markus/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pronto-0.8.1/lib/pronto.rb:56:in `run'
  /Users/markus/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pronto-0.8.1/lib/pronto/cli.rb:54:in `block in run'
  /Users/markus/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pronto-0.8.1/lib/pronto/cli.rb:53:in `chdir'
  /Users/markus/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pronto-0.8.1/lib/pronto/cli.rb:53:in `run'
  /Users/markus/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /Users/markus/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/markus/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /Users/markus/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /Users/markus/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pronto-0.8.1/bin/pronto:6:in `<top (required)>'
  /Users/markus/.rbenv/versions/2.3.3/bin/pronto:22:in `load'
  /Users/markus/.rbenv/versions/2.3.3/bin/pronto:22:in `<top (required)>'
```

I traced this back the Pronto::Coffeelint runner. Is this a Coffelint bug or pronto bug? ping @mmozuras

edit: fixed line numbers in backtrace (was one off because I inserted a debug puts)

**Comment by siebertm** [comment]
I had a similar problem yesterday in a project which didn't use pronto-coffeelint (i was using `pronto-eslint_npm` I think).

Since I was a bit under time pressure, I just downgraded to 0.7 and the problem disappeared.

Maybe 0.8 changed an API?

**Comment by doits** [comment]
Weird, I am the maintainer of `pronto-eslint_npm` and have not yet encountered the error (and the automatic test suite runs fine with pronto 0.8.1) - so maybe this only happens with some specific configuration?

**Comment by siebertm** [comment]
A quick search in my codebase reveals no `commit` method call...

**Comment by doits** [comment]
Yeah, the error happens in pronto ([/lib/pronto/runners.rb](https://github.com/mmozuras/pronto/blob/b68fc1621db5e998f5de47f81f9d6bbf2f1a989b/lib/pronto/runners.rb#L20)), but I don't know whether the return value is wrong or pronto is wrong ...

**Comment by siebertm** [comment]
so for my project with eslint_npm:

```
# bundle 
Using rake 12.0.0
Using public_suffix 2.0.5
Using multipart-post 2.0.0
Using json 1.8.6
Using multi_xml 0.6.0
Using unicode-display_width 1.1.3
Using rainbow 2.2.1
Using rugged 0.25.1.1
Using thor 0.19.4
Using bundler 1.14.5
Using addressable 2.5.0
Using faraday 0.11.0
Using httparty 0.13.7
Using terminal-table 1.7.3
Using sawyer 0.8.1
Using gitlab 3.7.0
Using octokit 4.6.2
Using pronto 0.8.1
Using pronto-eslint_npm 0.8.1
```

```
bx pronto run -c fix-tests
bundler: failed to load command: pronto (/home/siebert/.rbenv/versions/2.4.0/bin/pronto)
NoMethodError: undefined method `commit' for #<Array:0x005582fbc4c628>
  /home/siebert/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pronto-0.8.1/lib/pronto/runners.rb:20:in `block in run'
  /home/siebert/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pronto-0.8.1/lib/pronto/runners.rb:13:in `each'
  /home/siebert/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pronto-0.8.1/lib/pronto/runners.rb:13:in `run'
  /home/siebert/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pronto-0.8.1/lib/pronto.rb:56:in `run'
  /home/siebert/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pronto-0.8.1/lib/pronto/cli.rb:54:in `block in run'
  /home/siebert/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pronto-0.8.1/lib/pronto/cli.rb:53:in `chdir'
  /home/siebert/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pronto-0.8.1/lib/pronto/cli.rb:53:in `run'
  /home/siebert/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /home/siebert/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /home/siebert/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /home/siebert/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /home/siebert/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pronto-0.8.1/bin/pronto:6:in `<top (required)>'
```

So the same error...

**Comment by doits** [comment]
OK, found the errors, it's a pronto thing ... will open it there in a few moments (and link it here)

**Comment by siebertm** [comment]
it's already fixed in https://github.com/mmozuras/pronto/commit/b68fc1621db5e998f5de47f81f9d6bbf2f1a989b (not yet released)

**Comment by siebertm** [comment]
duplicate of https://github.com/mmozuras/pronto/pull/203

**Comment by doits** [comment]
yep, that was what I found, too. Was confused at first why [things like this](https://github.com/siebertm/pronto-coffeelint/blob/06fc9c066d36ddb7177ff78d35e777ef65bf3deb/lib/pronto/coffeelint.rb#L9-L12) work, because they convert the class, too, but there it looks like pronto expects an array at the end ...

maybe that pronto enumerable thing should be refactored then, but that's something for pronto, not the runners.
